name: lean-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets:ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret:SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Output file contents
        run: |
          cat ./test.conf
