name: lean-github-actions
on:
  push:
    tags:
      - '*-dev'

jobs:
  replace-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: File and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "alert@example.com"
          replace: "alert@replace.com"
          include: "subdir/test.conf"
          regex: false
        
      - name: Output file contents
        run: |
          cat ./test.conf ./subdir/test.conf
          
      - name: create artifacts archive
        run: |
          tar zcvf artifacts.tar.gz test.conf subdir/
      
      - name: Upload file to s3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          aws s3 cp artifacts.tar.gz s3://$S3_UPLOAD_BUCKET/ --quiet
          
